// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using UnityEngine.UI;

public class ScreenManager
{
	ScreenManager () {
	}

	private static ScreenManager _instance;

	public static ScreenManager instance() {
		if (_instance == null) {
			_instance = new ScreenManager();
		}

		return _instance;
	}

	public void registerScreen(string name, GameObject screen) {
		_namedScreens[name] = screen;
		screen.SetActive(false);
	}

	public void unregisterScreen(string name) {
		_namedScreens.Remove(name);
	}

	public void releaseAll() {
		_namedScreens.Clear();
	}

	public GameObject get(string name) {
		return (GameObject)_namedScreens[name];
	}

	public GameObject show(string name, bool showOrHide, string anim = "", bool directly = false) {
		GameObject screen = (GameObject)_namedScreens[name];
		if (screen != null) {
			show(screen, showOrHide, anim, directly);
		}

		return screen;
	}

	public static void show(GameObject screen, bool showOrHide, string anim = "", bool directly = false) {
		ScreenBase screenBase = screen.GetComponent<ScreenBase>();
		if (showOrHide) {
			screenBase.open(anim, directly);
		} else {
			screenBase.close(anim, directly);
		}

		screenBase.onShow(showOrHide);
	}

	public static void change(GameObject src, GameObject dst, string srcAnim = "", string dstAnim = "") {
		src.gameObject.GetComponent<ScreenBase>().close(srcAnim);
		dst.gameObject.GetComponent<ScreenBase>().open(dstAnim);
	}

	private Hashtable _namedScreens = new Hashtable();
}

